apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: churn-ingress
  namespace: churn-ml
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - churn.yourdomain.com
      secretName: churn-tls
  rules:
    - host: churn.yourdomain.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: churn-api-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: churn-dashboard-service
                port:
                  number: 8050
